baseURL: https://LennMass.github.io/
languageCode: en-us
defaultContentLanguage: en
title: Lennard Ma√ümann
theme: hermit
pygmentsCodefences: yes
pygmentsUseClasses: yes
rssLimit: 10
copyright: This work is licensed under a Creative Commons Attribution-NonCommercial
  4.0 International License.
enableEmoji: yes
author:
  name: John Doe
blackfriday: {}
taxonomies:
  tag: tags
params:
  code_copy_button: yes
  dateform: Jan 2, 2006
  dateformNum: '2006-01-02'
  dateformNumTime: 2006-01-02 15:04 -0700
  dateformShort: Jan 2
  footerCopyright: ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/"
    target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  homeSubtitle: Phd candidate in Econometrics.
  justifyContent: no
  relatedPosts: no
  social:
    - name: linkedin
      url: https://www.linkedin.com/in/lennard-ma%C3%9Fmann-67a0341a5/
    - name: github
      url: https://github.com/LennMass
  themeColor: '#494f5c'
menu:
  main:
    - name: Posts
      url: posts/
      weight: 10
    - name: About
      url: about-hugo/
      weight: 20
		- name: CV
      url: cv/
      weight: 20
